services:
  13ft:
    container_name: 13ft
    hostname: 13ft
    image: ghcr.io/wasi-master/13ft:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    healthcheck:
      test:
        - CMD
        - wget
        - '-q'
        - '--spider'
        - 'http://127.0.0.1:5000'
      interval: 2s
      timeout: 10s
      retries: 15
